framework:
    assets:
        packages:
            app:
                json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
            dashboard:
                json_manifest_path: '%kernel.project_dir%/public/dashboard/build/manifest.json'
