<?php

namespace ContainerWFx6Gfw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LshXhOFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lshXhOF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lshXhOF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'content' => ['privates', '.errored..service_locator.lshXhOF.App\\Entity\\Content', NULL, 'Cannot autowire service ".service_locator.lshXhOF": it references class "App\\Entity\\Content" but no such service exists.'],
        ], [
            'content' => 'App\\Entity\\Content',
        ]);
    }
}
