<?php

namespace ContainerWFx6Gfw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Dashboard\ContentController' shared autowired service.
     *
     * @return \App\Controller\Dashboard\ContentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Dashboard/ContentController.php';

        $container->services['App\\Controller\\Dashboard\\ContentController'] = $instance = new \App\Controller\Dashboard\ContentController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\ContentRepository'] ?? $container->load('getContentRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Dashboard\\ContentController', $container));

        return $instance;
    }
}
