<?php

namespace ContainerWFx6Gfw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ContentType' shared autowired service.
     *
     * @return \App\Form\ContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ContentType.php';

        return $container->privates['App\\Form\\ContentType'] = new \App\Form\ContentType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
