<?php

namespace ContainerWFx6Gfw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lshXhOF.App\Entity\Content' shared service.
     *
     * @return \App\Entity\Content
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lshXhOF": it references class "App\\Entity\\Content" but no such service exists.');
    }
}
