<?php

namespace ContainerWFx6Gfw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Dashboard\HomeController' shared autowired service.
     *
     * @return \App\Controller\Dashboard\HomeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Dashboard/HomeController.php';

        $container->services['App\\Controller\\Dashboard\\HomeController'] = $instance = new \App\Controller\Dashboard\HomeController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Dashboard\\HomeController', $container));

        return $instance;
    }
}
