<?php

namespace ContainerWFx6Gfw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHexadecimalColorValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\HexadecimalColorValidator' shared autowired service.
     *
     * @return \App\Validator\HexadecimalColorValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/HexadecimalColorValidator.php';

        return $container->privates['App\\Validator\\HexadecimalColorValidator'] = new \App\Validator\HexadecimalColorValidator();
    }
}
